### ISSUE TITLE
Clean up error messages to the client

### ISSUE THREAD

**Issue by bashir2** [google/fhir-gateway#100]
Right now, in many error cases, we send large stack-traces to the client. This is probably of little value to the proxy user and the proxy developer should have access to the logs (which is were these traces are already printed and should be kept).

**Comment by anchita-g** [comment]
I could not find any instance where stack-traces are sent back as response to the client. Closing this issue for now.

**Comment by bashir2** [comment]
For completeness:
This was originally filed in late 2021 in our internal system before open-sourcing and then imported to GitHub recently. I do not remember what exactly might have fixed this. But another portion of this bug (which I forgot to log in the main description) was: _"pass reasons for access denied decisions, e.g., when we cannot extract Patient ID from a new resource."_

I have not filed a separate bug for the last piece as I am not sure if that is really needed (given what is logged on the server side). We can reopen this bug or file another one when the need comes up.
