### ISSUE TITLE
Abstract out bundle processing in AccessCheckers to a separate entity

### ISSUE THREAD

**Issue by anchita-g** [google/fhir-gateway#104]
In reference to the conversation [here](https://github.com/google/fhir-gateway/pull/89#discussion_r1105272554) in [PR](https://github.com/google/fhir-gateway/pull/89) , remove the duplicated logic of Bundle processing in PatientAccessChecker. Possibly refactor any Bundle processing related code in other AccessCheckers as well.
Idea is to create a separate abstraction for Bundle processing which can be used by different implementations like PatientFinder and for any specific implementation of Bundle processing in the AccessCheckers.

**Comment by bashir2** [comment]
@anchita-g thanks for fixing the Bundle parsing duplication in #134; given that PR is merged, should we close this issue? I know we originally wanted to create a generic pattern for Bundle processing too but I think we established that we only address the performance part for now, correct? If yes, please feel free to close this issue.

Side note ICYDK: You can mention "fixes #<issue-number>" in a PR such that when it is merged it automatically closes the referenced issue <issue-number> too.

**Comment by anchita-g** [comment]
@bashir2 , yes we can close this issue. 
Thanks for sharing the "fixes #" hack.
