### ISSUE TITLE
EPIC: As ONA, I can use Gateway maven artifact for production use case without a fork

### ISSUE THREAD

**Issue by vivekmittal07** [google/fhir-gateway#108]
ONA has created a forked repo - https://github.com/opensrp/fhir-access-proxy

They have updated the server and the added their plugin. 
We should try to bring the server changes to the main repo and help them to just created their plugin using the released maven release for the server.

Sub-issues:
- #109 
- #115 
- #116 
- #117 
- #122

**Comment by bashir2** [comment]
Marking this as a requirement for the "Beta launch" to make sure our Maven release is in good shape.

**Comment by bashir2** [comment]
Thanks @vivekmittal07 for taking care of all the sub-issues. The only remaining issue is making a release for which I created #150.
