### ISSUE TITLE
Evaluate the changes done by ONA to the forked FHIR Gateway server component

### ISSUE THREAD

**Issue by vivekmittal07** [google/fhir-gateway#109]
Parent Issue - https://github.com/google/fhir-gateway/issues/108

**Comment by vivekmittal07** [comment]
Changes done in the forker repo

1. Skip token verification for allowed queries - https://github.com/opensrp/fhir-access-proxy/commit/55bb437a8060d27142980137b81e7432ef0c9aab
2. Modify Allowed queries checker to support path variables and method type validation - https://github.com/opensrp/fhir-access-proxy/commit/55bb437a8060d27142980137b81e7432ef0c9aab
3. [Resource finder](https://github.com/opensrp/fhir-access-proxy/blob/main/server/src/main/java/com/google/fhir/proxy/ResourceFinderImp.java) utility for processing bundles.
4. Enable preprocessing of request for an access decision - https://github.com/opensrp/fhir-access-proxy/commit/09584ef2bb5682bc3c9280ec1b72ad3432918019. 
5. Plugin specific [Proxy constants](https://github.com/opensrp/fhir-access-proxy/blob/main/server/src/main/java/com/google/fhir/proxy/ProxyConstants.java). 


4 & 5 are not needed in the server and can be easily moved to the plugin code.

**Comment by dubdabasoduba** [comment]
@vivekmittal07 4 has some OpenSRP-specific classes we might want to refactor that.

**Comment by dubdabasoduba** [comment]
The rest is correct

**Comment by vivekmittal07** [comment]
Thanks Benjamin!

I realised now why preprocess stage was introduced. 
I have created this to allow request mutation in the access checker design - https://github.com/google/fhir-gateway/issues/122
