### ISSUE TITLE
Allow unauthenticated requests for certain endpoints

### ISSUE THREAD

**Issue by vivekmittal07** [google/fhir-gateway#115]
Parent - https://github.com/google/fhir-gateway/issues/108

ONA requires capability to allow access without a valid access tokens for some APIs. We should allow unauthenticated allowed queries.

This  is used to fetch Composition and some Binary resources before login.

**Comment by jjtswan** [comment]
Oh, this seems like it should be targeted for the Beta right?  Since this is a blocker for ONA to use?

**Comment by jjtswan** [comment]
Can you comment a little more about the use case?  What's an example of a kind of API?

**Comment by vivekmittal07** [comment]
This is used to fetch Composition and some Binary resources before login. Updated the issue description as well.
