### ISSUE TITLE
Resource finder utility for processing bundles

### ISSUE THREAD

**Issue by vivekmittal07** [google/fhir-gateway#117]
Parent issue - https://github.com/google/fhir-gateway/issues/108 

Provide a resource finder for processing bundles similar to ONA's implementation - [Resource finder](https://github.com/opensrp/fhir-access-proxy/blob/main/server/src/main/java/com/google/fhir/proxy/ResourceFinderImp.java).

**Comment by bashir2** [comment]
We provide functionality to extract a Bundle from the request. Beyond that, what is required here seems to be access-checker specific and so probably should be left to the actual plugin implementation (not in the server). Removing this as a Beta launch blocker.

@vivekmittal07 please comment whether we need to close this issue or not. The course of action seems to be for ONA to move this logic out out `server`.

**Comment by vivekmittal07** [comment]
@bashir2 this is correct we don't need to do anything else here.

The utility methods created as part of https://github.com/google/fhir-gateway/pull/134 are sufficient for parsing the bundle and rest of the Resource finder functionality can be moved to the custom plugin.
