### ISSUE TITLE
Support gzip encoding for data transfer

### ISSUE THREAD

**Issue by anchita-g** [google/fhir-gateway#144]
We should support "gzip" encoding for fetching responses from the FHIR resource server, as this is crucial towards optimising for network bandwidth. The client can tell the server that it can accept the "gzip" encoding with `Accept-Encoding` header value

**Comment by bashir2** [comment]
Thanks @anchita-g for filing this. Just to clarify, there are two parts for full support of gzip: (1) communication with the client, e.g., an Android/web app (2) communication between the gateway and the FHIR server. We should handle both but (1) is probably more important for the motivation mentioned in the issue. Also [this is a TODO](https://github.com/google/fhir-gateway/blob/85c9bfabc84e7e2ff21fbe74b1aed577d2a08272/server/src/main/java/com/google/fhir/gateway/BearerAuthorizationInterceptor.java#L303) related to this.
