### ISSUE TITLE
Check for all patients access in ListAccessChecker for deletion in Bundle

### ISSUE THREAD

**Issue by anchita-g** [google/fhir-gateway#162]
The `ListAccessChecker` will allow deletion of all resources even if any one of the patients referenced in the deletion bundle request is allowed to be accessed. We should check the access to all the patients referenced in the deletion bundle request and only if all the patients are allowed to be accessed, should we allow the query to pass through.

**Comment by bashir2** [comment]
@anchita-g is this bug now fixed with #160?
