### ISSUE TITLE
Support DELETE operations

### ISSUE THREAD

**Issue by bashir2** [google/fhir-gateway#43]
We currently do not support `DELETE` operations in the access-checkers; we should fix this.

It's currently a P3 because it is not clear how important it is for the immediate use-cases we know of.

**Comment by vivekmittal07** [comment]
There are 2 types of delete operation supported by FHIR - http://go/fhirs/http.html#delete
1. **Delete by resource Id** -  This doesn't support any query parameters.
To authorize this request we need to first fetch the target resource and check if the caller has access to the patient attached to that resource. 
We cannot make this decision just based on the incoming request.
If we support this then we can also potentially support Get by ID api. Currently we only accept search queries. 

2. **Conditional delete** _(Experimental)_: This deletes based on the search query passed by the client.
We can support bulk delete operation with this approach with a caveat that the search should be scoped to a patient. 
This is supported by HAPI but conditional mutates are marked experimental features in the spec. 

@bashir2 
What type of Delete operation do we want to support here ?

**Comment by bashir2** [comment]
@vivekmittal07 for now I think we can focus on the second type of delete. The issue you mentioned (i.e., fetch/mutate by resource ID) is a common one for which I created issue #63 and we can track it there.

**Comment by bashir2** [comment]
@vivekmittal07 with #76 merged is there anything else that we need to do here, or can we close this?

**Comment by vivekmittal07** [comment]
nothing else is remaining. We can close this now.
