### ISSUE TITLE
Support extracting all patient IDs when URL contains ORs

### ISSUE THREAD

**Issue by bashir2** [google/fhir-gateway#45]
Reported by @omarismail94 

The proxy does not support having ORs in search parameters. 

If I do a direct request to GCP FHIR Store, it works:
```
curl -X GET -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
  -H "Content-Type: application/json; charset=utf-8" \
  "https://healthcare.googleapis.com/v1alpha2/projects/[PROJECT]/locations/us/datasets/[DATASET]/fhirStores/gcs-data/fhir/Observation?_id=3f6cb1cf-2c0d-739d-0790-5ab8a26daf2e&subject=Patient/92a950eb-6aae-0e82-c297-d91585b22edf,performer=Patient/123"
```

If I send the same to proxy, I get an error saying that the patient id cannot be found.

Also we should turn any request that has searches that contain OR, e.g. subject=P1,P2 into an access check for both P1 AND P2, i.e. client should have access to P1 and P2.

**Comment by jjtswan** [comment]
Do we think this needs to be part of Beta?

**Comment by jjtswan** [comment]
Okay, sounds like this should be part of the Beta and is attached to the E2E sync workstream.   Possible that we might get to it sooner depending on bandwidth.

Key use case is that this is helpful for creating batched resource fetches to reduce RTT and network bandwidth.

**Comment by jjtswan** [comment]
If we don't support this explicitly, we should probably reject requests that use OR.  Can we confirm?

**Comment by anchita-g** [comment]
@jjtswan the PR #160 is linked to this already.
